server {
    listen 80;
    server_name localhost;

    # 指定打包後的文件保存目錄
    root /usr/share/nginx/html;

    index index.html;

    # Vue Router 的 fallback 支持 (解決SPA頁面刷新404問題)
    location / {
        try_files $uri /index.html;
    }

    # 確保靜態資源正常運行
    location /assets {
        try_files $uri =404;
    }

    error_page 404 /index.html;  # 處理 404 由 Vue 日後處理
}